apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
spec:
  template:
    spec:
      containers:
      - name: my-container
        image: busybox:latest
        command:
          - "/bin/sh"
          - "-c"
          - "echo Key1: $(cat /config/config.yaml | grep 'key1:' | awk '{print $2}') && echo Key2: $(cat /config/config.yaml | grep 'key2:' | awk '{print $2}')"
        volumeMounts:
        - name: config-volume
          mountPath: /config
      volumes:
      - name: config-volume
        configMap:
          name: my-config
  backoffLimit: 3
