# job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: my3-jo
spec:
  template:
    spec:
      containers:
      - name: my-container
        image: busybox
        command: ["/bin/sh", "-c", "echo Variable1: $variable1 && echo Variable2: $variable2"]
        envFrom:
        - configMapRef:
            name: my-config1
      restartPolicy: Never
